### ISSUE TITLE
[BUG] Query about weather forecast raises an exception

### ISSUE THREAD

**Issue by Lilja** [NeonGeckoCom/skill-wikipedia#27]
### Description

I asked my mark 2, "hey neon, tell me about tomorrow's weather forecast". It tried to query that information from wikipedia.

### Steps to Reproduce

-  "hey neon, tell me about tomorrow's weather forecast"

### Other Notes

https://matrix.to/#/!ZhEZYNzKBfpEAhtQIz:matrix.org/$4RGxN1mYABoU0M5GkkYAMqp_LvF-MN8wUXPlk49tHQI?via=matrix.org&via=strugee.net&via=beeper.com
https://github.com/NeonGeckoCom/skill-weather/issues/48

`voice.log`

```
2023-08-31 03:26:33.341 - skills - neon_core.skills.intent_service:handle_utterance:229 - INFO - ["tell me about tomorrow's weather forecast"]
2023-08-31 03:26:34.562 - skills - ovos_utils.gui:_normalize_page_name:835 - WARNING - Deprecation version=0.1.0. Caller=skill_wikipedia:71. GUI resources should exclude gui-specific file extensions. This call should probably pass `SYSTEM_AnimatedImageFrame`, instead of `SYSTEM_AnimatedImageFrame.qml`
2023-08-31 03:26:35.970 - skills - ovos_utils.file_utils:resolve_resource_file:152 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
2023-08-31 03:26:36.190 - skill-wikipedia.neongeckocom - ERROR - string indices must be integers
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.10/site-packages/ovos_utils/messagebus.py", line 554, in wrapper
    handler(message)
  File "/home/neon/venv/lib/python3.10/site-packages/skill_wikipedia/__init__.py", line 83, in handle_wiki_query
    self._speak_wiki(data, get_message_user(message))
  File "/home/neon/venv/lib/python3.10/site-packages/skill_wikipedia/__init__.py", line 117, in _speak_wiki
    self.current_picture = data["images"]
TypeError: string indices must be integers
```

**Comment by NeonDaniel** [comment]
Appears to be resolved by adopting OVOS' Wiki skill

**Comment by NeonDaniel** [comment]
Replacing this skill with [skill-ovos-wikipedia](https://github.com/OpenVoiceOS/skill-ovos-wikipedia) in Neon OS defaults
